name: Release Gist Apple
run-name: Release gist-apple

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GIST_COCOAPODS_TRUNK_TOKEN: ${{ secrets.GIST_COCOAPODS_TRUNK_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
          fetch-depth: 0
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Deploy Cocoapods
        uses: michaelhenry/deploy-to-cocoapods-github-action@1.0.10
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ env.GIST_COCOAPODS_TRUNK_TOKEN }}        